version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: french-novel-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      # Use DATABASE_URL from .env if connecting to Supabase, otherwise default to SQLite
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app.db}
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000
      - LOG_LEVEL=DEBUG
      - RATELIMIT_ENABLED=False
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.venv
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: french-novel-frontend-dev
    ports:
      - "3000:3000"
      - "6006:6006"  # Storybook
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=https://api.frenchnoveltool.com/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: french-novel-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  redis-data-dev:

networks:
  app-network:
    driver: bridge

