"""Application-wide constants"""

# Default configuration values
DEFAULT_SENTENCE_LENGTH_LIMIT = 8
DEFAULT_MAX_FILE_SIZE_MB = 50

# Rate limiting defaults
DEFAULT_RATE_LIMIT = "100 per hour"
PROCESS_PDF_RATE_LIMIT = "10 per hour"
EXPORT_SHEET_RATE_LIMIT = "20 per hour"

# Validation limits
MIN_SENTENCE_LENGTH_LIMIT = 3
MAX_SENTENCE_LENGTH_LIMIT = 50
MAX_SENTENCES_PER_REQUEST = 10000
MAX_SENTENCE_LENGTH = 5000
MAX_SHEET_NAME_LENGTH = 255

# API versioning
API_VERSION = "1.0.0"
API_SERVICE_NAME = "French Novel Tool API"

# File upload
ALLOWED_FILE_EXTENSIONS = {'pdf'}

# Gemini API
DEFAULT_GEMINI_MODEL = 'gemini-2.5-flash'
DEFAULT_GEMINI_MAX_RETRIES = 3
DEFAULT_GEMINI_RETRY_DELAY = 1

# Logging
DEFAULT_LOG_LEVEL = 'INFO'
LOG_MAX_BYTES = 10 * 1024 * 1024  # 10MB
LOG_BACKUP_COUNT = 10

