"""Add google Auth

Revision ID: 1da9a0c3a2ac
Revises: add_p1_feature_fields
Create Date: 2025-10-03 08:56:41.744583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da9a0c3a2ac'
down_revision = 'add_p1_feature_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_original_filename'), ['original_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_timestamp'), ['timestamp'], unique=False)

    # Skip constraint dropping for SQLite as it doesn't always track them correctly
    # The unique constraint on user_id is defined in the model and will be enforced

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip constraint recreation for SQLite

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_history_original_filename'))

    # ### end Alembic commands ###
