"""Add google Auth

Revision ID: 1da9a0c3a2ac
Revises: add_p1_feature_fields
Create Date: 2025-10-03 08:56:41.744583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da9a0c3a2ac'
down_revision = 'add_p1_feature_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_original_filename'), ['original_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_settings_user_id_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_google_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_google_id_key'), ['google_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_settings_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_history_original_filename'))

    # ### end Alembic commands ###
