"""Add async processing fields to Job model

Revision ID: 48fd2dc76953
Revises: e1b51492b2e1
Create Date: 2025-10-04 04:05:40.946914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fd2dc76953'
down_revision = 'e1b51492b2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sa.String(length=155), nullable=True))
        batch_op.add_column(sa.Column('progress_percent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chunk_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('failed_chunks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_time_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_calls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gemini_tokens_used', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_celery_task_id'))
        batch_op.drop_column('gemini_tokens_used')
        batch_op.drop_column('gemini_api_calls')
        batch_op.drop_column('processing_time_seconds')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('max_retries')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('failed_chunks')
        batch_op.drop_column('chunk_results')
        batch_op.drop_column('processed_chunks')
        batch_op.drop_column('total_chunks')
        batch_op.drop_column('current_step')
        batch_op.drop_column('progress_percent')
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###
