"""Add authentication system

Revision ID: 6deaf3110825
Revises: 
Create Date: 2025-10-02 05:04:47.538599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6deaf3110825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('picture', sa.String(length=512), nullable=True),
        sa.Column('google_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    
    # Add user_id to history table
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_history_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_history_user_id', 'users', ['user_id'], ['id'])

    # Add user_id to user_settings table
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key('fk_user_settings_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove user_id from user_settings table
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_settings_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_column('user_id')

    # Remove user_id from history table
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_history_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_history_user_id'))
        batch_op.drop_column('user_id')

    # Drop users table
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
