"""Add OAuth token fields to User model

Revision ID: 997f943cdd21
Revises: 6deaf3110825
Create Date: 2025-10-02 06:17:37.773095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997f943cdd21'
down_revision = '6deaf3110825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip history and user_settings changes - already manually applied
    # Only add the OAuth token fields to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove the OAuth token fields from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    # ### end Alembic commands ###
