"""Add status column to history table

Revision ID: add_status_to_history
Revises: add_processing_metadata
Create Date: 2025-10-13 10:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_status_to_history'
down_revision = 'add_processing_metadata'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='complete'))
        batch_op.create_index('ix_history_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###