"""Add credit system tables and job tracking

Revision ID: e1b51492b2e1
Revises: 1da9a0c3a2ac
Create Date: 2025-10-03 11:20:50.747186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b51492b2e1'
down_revision = '1da9a0c3a2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(length=128), nullable=True),
    sa.Column('processed_sentences_count', sa.Integer(), nullable=True),
    sa.Column('spreadsheet_url', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('failed_step', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('processing_settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_original_filename'), ['original_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_credits', sa.Integer(), nullable=False),
    sa.Column('actual_credits', sa.Integer(), nullable=True),
    sa.Column('pricing_version', sa.String(length=20), nullable=False),
    sa.Column('pricing_rate', sa.Float(), nullable=False),
    sa.Column('processing_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_history_id'), ['history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=512), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('delta_credits', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('pricing_version', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_user_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sentence_length_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gemini_model', sa.String(length=50), nullable=True),
    sa.Column('ignore_dialogue', sa.Boolean(), nullable=True),
    sa.Column('preserve_formatting', sa.Boolean(), nullable=True),
    sa.Column('fix_hyphenation', sa.Boolean(), nullable=True),
    sa.Column('min_sentence_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_timestamp'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_reason'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_month'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_job_id'))
        batch_op.drop_index('idx_user_month')

    op.drop_table('credit_ledger')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_history_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_history_original_filename'))
        batch_op.drop_index(batch_op.f('ix_history_job_id'))

    op.drop_table('history')
    # ### end Alembic commands ###
