"""vocab_coverage_v2

Revision ID: vocab_coverage_v2
Revises: 0299e3b2e149
Create Date: 2025-10-10 05:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'vocab_coverage_v2'
down_revision = '0299e3b2e149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
